const kidsData = [
  {
    brand: "Barakah Kids",
    product_name: "Blue Cotton Shirt",
    sku: "BK-KD-001",
    sizes: "2, 4, 6, 8",
    fabric: "Cotton",
    set_type: "Shirt",
    color: "Blue",
    pattern: "Plain",
    sleeve_length: "Full",
    occasion: "Casual",
    price_in_tk: 1200,
    discount: true,
    discount_price: 1000,
    image: "https://example.com/kids-blue-shirt.jpg",
    video: "https://www.youtube.com/embed/aBcDeFgH01",
  },
  {
    brand: "Little Noor",
    product_name: "Red Party Dress",
    sku: "LN-KD-002",
    sizes: "2, 4, 6",
    fabric: "Cotton Blend",
    set_type: "Dress",
    color: "Red",
    pattern: "Floral",
    sleeve_length: "Short",
    occasion: "Party",
    price_in_tk: 1800,
    discount: false,
    discount_price: 1800,
    image: "https://example.com/kids-red-dress.jpg",
    video: "https://www.youtube.com/embed/bCdEfGhI02",
  },
  {
    brand: "Deshi Kids",
    product_name: "Green Casual T-shirt",
    sku: "DK-KD-003",
    sizes: "2, 4, 6, 8",
    fabric: "Cotton",
    set_type: "T-shirt",
    color: "Green",
    pattern: "Printed",
    sleeve_length: "Short",
    occasion: "Casual",
    price_in_tk: 900,
    discount: true,
    discount_price: 750,
    image: "https://example.com/kids-green-tshirt.jpg",
    video: "https://www.youtube.com/embed/cDeFgHiJ03",
  },
  {
    brand: "Heritage Kids",
    product_name: "Yellow Summer Shorts",
    sku: "HK-KD-004",
    sizes: "2, 4, 6",
    fabric: "Linen",
    set_type: "Shorts",
    color: "Yellow",
    pattern: "Solid",
    sleeve_length: "N/A",
    occasion: "Summer",
    price_in_tk: 1500,
    discount: false,
    discount_price: 1500,
    image: "https://example.com/kids-yellow-shorts.jpg",
    video: "https://www.youtube.com/embed/dEfGhIjK04",
  }
];

export default kidsData;
