const data = [
  {
    "brand": "Barakah Shop",
    "product_name": "Classic Cotton Panjabi",
    "sku": "BS-PB-001",
    "sizes": "38, 40, 42, 44",
    "fabric": "100% Cotton",
    "style": "Classic",
    "color": "White",
    "pattern": "Plain",
    "sleeve_length": "Full",
    "occasion": "Casual / Jummah",
    "price_in_tk": 1800,
    "image": "https://static-01.daraz.com.bd/p/0cb12cbdcd6d8f76c6d8f3099d0d21fc.jpg",
    "video": "https://www.youtube.com/embed/aBcDeFgH01",
    "discount": true,
    "discount_price": 1500
  },
  {
    "brand": "Noor Wear",
    "product_name": "Black Embroidered Panjabi",
    "sku": "NW-PB-002",
    "sizes": "38, 40, 42, 44",
    "fabric": "Cotton Blend",
    "style": "Embroidered",
    "color": "Black",
    "pattern": "Neck Embroidery",
    "sleeve_length": "Full",
    "occasion": "Festive / Eid",
    "price_in_tk": 2500,
    "image": "https://static-01.daraz.com.bd/p/8e71dfbf5f1dffb2a5f72e7c0fb4b830.jpg",
    "video": "https://www.youtube.com/embed/bCdEfGhI02",
    "discount": false,
    "discount_price": 2500
  },
  {
    "brand": "Deshi Attire",
    "product_name": "Pastel Blue Panjabi",
    "sku": "DA-PB-003",
    "sizes": "38, 40, 42",
    "fabric": "Cotton",
    "style": "Minimal",
    "color": "Pastel Blue",
    "pattern": "Solid",
    "sleeve_length": "Full",
    "occasion": "Casual / Friday",
    "price_in_tk": 2000,
    "image": "https://static-01.daraz.com.bd/p/1e9b86504fcdcd28b061ef8ffad4f7a8.jpg",
    "video": "https://www.youtube.com/embed/cDeFgHiJ03",
    "discount": true,
    "discount_price": 1700
  },
  {
    "brand": "Heritage",
    "product_name": "Golden Premium Panjabi",
    "sku": "HT-PB-004",
    "sizes": "40, 42, 44",
    "fabric": "Silk Blend",
    "style": "Premium",
    "color": "Golden",
    "pattern": "Jacquard Weave",
    "sleeve_length": "Full",
    "occasion": "Wedding / Mehendi",
    "price_in_tk": 4500,
    "image": "https://static-01.daraz.com.bd/p/1c81cb2f61a2b7b4f3b3b0d56b5f77b6.jpg",
    "video": "https://www.youtube.com/embed/dEfGhIjK04",
    "discount": false,
    "discount_price": 4500
  },
  {
    "brand": "Barakah Shop",
    "product_name": "Olive Green Panjabi",
    "sku": "BS-PB-005",
    "sizes": "38, 40, 42",
    "fabric": "Cotton",
    "style": "Casual",
    "color": "Olive Green",
    "pattern": "Plain",
    "sleeve_length": "Full",
    "occasion": "Daily Wear",
    "price_in_tk": 1900,
    "image": "https://static-01.daraz.com.bd/p/3923b2a4e5d84e4d9b7e0b6e75c9654c.jpg",
    "video": "https://www.youtube.com/embed/eFgHiJkL05",
    "discount": true,
    "discount_price": 1650
  },
  {
    "brand": "Ethnic Wear",
    "product_name": "Rust Orange Panjabi",
    "sku": "EW-PB-006",
    "sizes": "40, 42, 44",
    "fabric": "Cotton",
    "style": "Festive",
    "color": "Rust Orange",
    "pattern": "Solid",
    "sleeve_length": "Full",
    "occasion": "Eid / Event",
    "price_in_tk": 2800,
    "image": "https://static-01.daraz.com.bd/p/2d429cf1d87e88d5c95b3a9b8324e784.jpg",
    "video": "https://www.youtube.com/embed/fGhIjKlM06",
    "discount": false,
    "discount_price": 2800
  },
  {
    "brand": "Noor Wear",
    "product_name": "Grey Mandarin Collar Panjabi",
    "sku": "NW-PB-007",
    "sizes": "38, 40, 42",
    "fabric": "Cotton Blend",
    "style": "Casual",
    "color": "Grey",
    "pattern": "Plain",
    "sleeve_length": "Full",
    "occasion": "Office / Friday",
    "price_in_tk": 2100,
    "image": "https://static-01.daraz.com.bd/p/7e5a6b5fc64f8cfcb3b52b99b5e8f1f7.jpg",
    "video": "https://www.youtube.com/embed/gHiJkLmN07",
    "discount": true,
    "discount_price": 1800
  },
  {
    "brand": "Deshi Attire",
    "product_name": "Navy Blue Casual Panjabi",
    "sku": "DA-PB-008",
    "sizes": "40, 42, 44",
    "fabric": "Cotton",
    "style": "Minimal",
    "color": "Navy Blue",
    "pattern": "Solid",
    "sleeve_length": "Full",
    "occasion": "Casual",
    "price_in_tk": 1950,
    "image": "https://static-01.daraz.com.bd/p/899cb22db83f6344f1cf07f77b9d7a10.jpg",
    "video": "https://www.youtube.com/embed/hIjKlMnO08",
    "discount": false,
    "discount_price": 1950
  },
  {
    "brand": "Heritage",
    "product_name": "White Luxury Kurta",
    "sku": "HT-PB-009",
    "sizes": "40, 42, 44, 46",
    "fabric": "Premium Cotton",
    "style": "Luxury",
    "color": "White",
    "pattern": "Self Texture",
    "sleeve_length": "Full",
    "occasion": "Wedding / Reception",
    "price_in_tk": 5000,
    "image": "https://static-01.daraz.com.bd/p/649b0710ecfbaeb5a7d4b49f3f2e5a66.jpg",
    "video": "https://www.youtube.com/embed/iJkLmNoP09",
    "discount": true,
    "discount_price": 4300
  },
  {
    "brand": "Barakah Shop",
    "product_name": "Cream Panjabi with Embroidery",
    "sku": "BS-PB-010",
    "sizes": "38, 40, 42",
    "fabric": "Cotton",
    "style": "Embroidered",
    "color": "Cream",
    "pattern": "Chest Embroidery",
    "sleeve_length": "Full",
    "occasion": "Festive",
    "price_in_tk": 2700,
    "image": "https://static-01.daraz.com.bd/p/2f8029a4c9afca3d4864c5d5bfc4c158.jpg",
    "video": "https://www.youtube.com/embed/jKlMnOpQ10",
    "discount": false,
    "discount_price": 2700
  },
  {
    "brand": "Ethnic Wear",
    "product_name": "Deep Maroon Panjabi",
    "sku": "EW-PB-011",
    "sizes": "40, 42, 44",
    "fabric": "Cotton Silk",
    "style": "Premium",
    "color": "Deep Maroon",
    "pattern": "Plain",
    "sleeve_length": "Full",
    "occasion": "Wedding / Eid",
    "price_in_tk": 3200,
    "image": "https://static-01.daraz.com.bd/p/63fb90581e2c8ff5a9e401cdbf23a9d7.jpg",
    "video": "https://www.youtube.com/embed/kLmNoPqR11",
    "discount": true,
    "discount_price": 2800
  },
  {
    "brand": "Deshi Attire",
    "product_name": "Mustard Yellow Panjabi",
    "sku": "DA-PB-012",
    "sizes": "38, 40, 42, 44",
    "fabric": "Cotton",
    "style": "Casual",
    "color": "Mustard Yellow",
    "pattern": "Solid",
    "sleeve_length": "Full",
    "occasion": "Day Out / Jummah",
    "price_in_tk": 2200,
    "image": "https://static-01.daraz.com.bd/p/f31fa70e4c946f308a8c7c2c6f6a1e1a.jpg",
    "video": "https://www.youtube.com/embed/lMnOpQrS12",
    "discount": false,
    "discount_price": 2200
  },
  {
    "brand": "Noor Wear",
    "product_name": "Teal Blue Panjabi",
    "sku": "NW-PB-013",
    "sizes": "38, 40, 42",
    "fabric": "Cotton",
    "style": "Semi-Formal",
    "color": "Teal Blue",
    "pattern": "Minimal Work",
    "sleeve_length": "Full",
    "occasion": "Semi-Formal",
    "price_in_tk": 2600,
    "image": "https://static-01.daraz.com.bd/p/14636e2b6fc7b7cba858b41bbd21fabc.jpg",
    "video": "https://www.youtube.com/embed/mNoPqRsT13",
    "discount": true,
    "discount_price": 2300
  },
  {
    "brand": "Barakah Shop",
    "product_name": "Light Pink Panjabi",
    "sku": "BS-PB-014",
    "sizes": "38, 40, 42",
    "fabric": "Cotton",
    "style": "Casual",
    "color": "Light Pink",
    "pattern": "Solid",
    "sleeve_length": "Full",
    "occasion": "Casual / Summer",
    "price_in_tk": 2000,
    "image": "https://static-01.daraz.com.bd/p/0a3b6e23a5ff31ec8e63b57cc3f3d819.jpg",
    "video": "https://www.youtube.com/embed/nOpQrStU14",
    "discount": false,
    "discount_price": 2000
  },
  {
    "brand": "Ethnic Wear",
    "product_name": "Bottle Green Panjabi",
    "sku": "EW-PB-015",
    "sizes": "40, 42, 44",
    "fabric": "Cotton",
    "style": "Minimal",
    "color": "Bottle Green",
    "pattern": "Plain",
    "sleeve_length": "Full",
    "occasion": "Casual / Friday",
    "price_in_tk": 2300,
    "image": "https://static-01.daraz.com.bd/p/f7b370e44e25b4b0f4e8e5fb08e4b43f.jpg",
    "video": "https://www.youtube.com/embed/oPqRsTuV15",
    "discount": true,
    "discount_price": 2000
  }
];

export default data;
