const organicData = [
  {
    brand: "Barakah Organics",
    product_name: "Organic Brown Rice",
    sku: "BO-OG-001",
    size: "1 KG",
    material: "Whole Grain",
    category: "Rice & Grains",
    color: "Brown",
    style: "Unpolished",
    occasion: "Daily Cooking",
    price_in_tk: 220,
    image:
      "https://img.freepik.com/free-photo/raw-brown-rice-wooden-bowl_1150-42479.jpg?semt=ais_incoming&w=740&q=80",
    video: "https://www.youtube.com/embed/aBcD123Rice",
    discount: true,
    discount_price: 200,
  },
  {
    brand: "Nature's Basket",
    product_name: "Organic Honey",
    sku: "NB-OG-002",
    size: "500 ML",
    material: "Pure Honey",
    category: "Natural Sweeteners",
    color: "Golden",
    style: "Raw & Unprocessed",
    occasion: "Health Drink / Dessert",
    price_in_tk: 550,
    image:
      "https://img.freepik.com/free-photo/honey-jar-with-dipper_144627-18439.jpg?semt=ais_incoming&w=740&q=80",
    video: "https://www.youtube.com/embed/bCdE456Honey",
    discount: false,
    discount_price: 550,
  },
  {
    brand: "Deshi Organics",
    product_name: "Organic Lentils (Masoor Dal)",
    sku: "DO-OG-003",
    size: "1 KG",
    material: "Pulses",
    category: "Lentils & Pulses",
    color: "Orange Red",
    style: "Chemical-Free",
    occasion: "Daily Meal",
    price_in_tk: 180,
    image:
      "https://img.freepik.com/free-photo/masoor-dal-lentils-bowl_114579-76028.jpg?semt=ais_incoming&w=740&q=80",
    video: "https://www.youtube.com/embed/cDeF789Lentil",
    discount: true,
    discount_price: 160,
  },
  {
    brand: "Pure Harvest",
    product_name: "Organic Coconut Oil",
    sku: "PH-OG-004",
    size: "250 ML",
    material: "Cold Pressed Oil",
    category: "Cooking Oil",
    color: "Transparent",
    style: "Cold-Pressed",
    occasion: "Cooking / Skincare",
    price_in_tk: 600,
    image:
      "https://img.freepik.com/free-photo/coconut-oil-fresh-coconuts_1150-16042.jpg?semt=ais_incoming&w=740&q=80",
    video: "https://www.youtube.com/embed/dEfG101Oil",
    discount: false,
    discount_price: 600,
  },
  {
    brand: "Green Farm",
    product_name: "Organic Turmeric Powder",
    sku: "GF-OG-005",
    size: "200 GM",
    material: "Turmeric Root",
    category: "Spices",
    color: "Golden Yellow",
    style: "Stone-Ground",
    occasion: "Cooking / Health Remedy",
    price_in_tk: 140,
    image:
      "https://img.freepik.com/free-photo/wooden-bowl-full-turmeric-powder_114579-77665.jpg?semt=ais_incoming&w=740&q=80",
    video: "https://www.youtube.com/embed/eFgH112Turmeric",
    discount: true,
    discount_price: 120,
  },
  {
    brand: "Ethnic Greens",
    product_name: "Organic Spinach (Palong Shak)",
    sku: "EG-OG-006",
    size: "500 GM",
    material: "Leafy Vegetable",
    category: "Fresh Vegetables",
    color: "Dark Green",
    style: "Freshly Harvested",
    occasion: "Salad / Curry",
    price_in_tk: 90,
    image:
      "https://img.freepik.com/free-photo/fresh-spinach-bunch_1150-7925.jpg?semt=ais_incoming&w=740&q=80",
    video: "https://www.youtube.com/embed/fGhI113Spinach",
    discount: false,
    discount_price: 90,
  },
];

export default organicData;
