const showpieceData = [
  {
    brand: "Barakah Shop",
    product_name: "Wooden Elephant Showpiece",
    sku: "BS-SP-001",
    size: "Medium",
    material: "Wood",
    category: "Animal Figurine",
    color: "Brown",
    style: "Handcrafted",
    occasion: "Home Decor",
    price_in_tk: 1800,
    image:
      "https://img.freepik.com/free-photo/wooden-elephant-indoors_23-2150801847.jpg?semt=ais_incoming&w=740&q=80",
    video: "https://www.youtube.com/embed/aBcDeFgH01",
    discount: true,
    discount_price: 1500,
  },
  {
    brand: "Noor Decor",
    product_name: "Golden Metal Horse",
    sku: "ND-SP-002",
    size: "Large",
    material: "Metal",
    category: "Luxury Showpiece",
    color: "Golden",
    style: "Antique Finish",
    occasion: "Office Table / Drawing Room",
    price_in_tk: 2500,
    image:
      "https://png.pngtree.com/png-vector/20240902/ourmid/pngtree-beautiful-3d-metal-golden-horse-with-mane-and-tail-hair-showing-png-image_13719947.png",
    video: "https://www.youtube.com/embed/bCdEfGhI02",
    discount: false,
    discount_price: 2500,
  },
  {
    brand: "Deshi Craft",
    product_name: "Ceramic Flower Vase",
    sku: "DC-SP-003",
    size: "Tall",
    material: "Ceramic",
    category: "Vase",
    color: "Pastel Blue",
    style: "Minimal",
    occasion: "Living Room Decor",
    price_in_tk: 2000,
    image:
      "https://c8.alamy.com/comp/TT8A8N/victorian-large-ceramic-flower-vase-with-gilded-handle-and-english-flower-decoration-TT8A8N.jpg",
    video: "https://www.youtube.com/embed/cDeFgHiJ03",
    discount: true,
    discount_price: 1700,
  },
  {
    brand: "Heritage Craft",
    product_name: "Glass Crystal Globe",
    sku: "HC-SP-004",
    size: "Small",
    material: "Glass",
    category: "Desk Decoration",
    color: "Transparent",
    style: "Premium",
    occasion: "Gift / Office Desk",
    price_in_tk: 4500,
    image:
      "https://m.media-amazon.com/images/I/71YO9oT-QhL._AC_SL1500_.jpg",
    video: "https://www.youtube.com/embed/dEfGhIjK04",
    discount: false,
    discount_price: 4500,
  }
];

export default showpieceData;
